---
- name: Deploying with Kubernetes
  hosts: localhost
  tasks:
    - name: create backend deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './deploy-backend.yaml') | from_yaml }}"
    - name: create backend service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './service-backend.yaml') | from_yaml }}" 
