---
- name: Deploying with Kubernetes
  hosts: localhost
  remote_user: dhamodhar
  tasks:
    - name: create backend deployment
      kubernetes.core.k8s:
        definition: "{{ lookup('file', './deploy-backend.yaml') | from_yaml }}"
        state: present
    - name: create backend service
      kubernetes.core.k8s:
        definition: "{{ lookup('file', './service-backend.yaml') | from_yaml }}" 
        state: present
