apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: socket-port
      protocol: TCP
      port: 3001
      targetPort: 3001
    - name: api-port
      port: 3002
      targetPort: 3002
      protocol: TCP
